# Generated by Django 5.0 on 2024-02-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_userwallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwallet",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
